version: "3.8"
services:
  mongo:
    image: mongo:7
    container_name: postcraft-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: postcraft
    volumes:
      - mongo_data:/data/db

  qdrant:
    image: qdrant/qdrant:latest
    container_name: postcraft-qdrant
    ports:
      - "6333:6333"   # HTTP
      - "6334:6334"   # gRPC
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  mongo_data:
  qdrant_data: